export const SET_ACCOUNT_PROFILE = 'SET_ACCOUNT_PROFILE';
export const SET_ACCOUNT_SECURITY = 'SET_ACCOUNT_SECURITY';
export const SET_ACCOUNT_COMMISSION_BALANCE = 'SET_ACCOUNT_COMMISSION_BALANCE';
export const SET_ACCOUNT_WEBSITE = 'SET_ACCOUNT_WEBSITE';
