export const CREATE_AFFILIATE_ACCOUNT = 'CREATE_AFFILIATE_ACCOUNT';
export const AVAILABLE_AFFILIATE_ACCOUNT = 'AVAILABLE_AFFILIATE_ACCOUNT';
export const AVAILABLE_AFFILIATE_EMAIL = 'AVAILABLE_AFFILIATE_EMAIL';
export const AVAILABLE_AFFILIATE_CAPTCHA = 'AVAILABLE_AFFILIATE_CAPTCHA';

