export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AUTH_MESSAGE ='AUTH_MESSAGE'
export const CHECK_SESSION_EXPIRED ='CHECK_SESSION_EXPIRED'
export const REDIRECT_TO_188MEMBERSITE ='REDIRECT_TO_188MEMBERSITE'