export const SET_COLLATERAL_LIST = 'SET_COLLATERAL_LIST';
export const SET_LINK_LIST = 'SET_LINK_LIST';
export const SET_COLLATERAL_CLASSIFICATION_LIST = 'SET_COLLATERAL_CLASSIFICATION_LIST';
export const SET_SCRIPT = 'SET_SCRIPT';
